### ISSUE TITLE
interval matrix

### ISSUE THREAD

**Issue by marwaSaid** [leggedrobotics/rayen#2]
Does RAYEN support interval matrices in Linear matrix inequalities?

**Comment by jtorde** [comment]
Hi @marwaSaid, 

Which type of constraints would you like to impose with the interval matrices? I guess you mean having F0,...,F_k being interval matrices in the LMI constraint, and then finding a y that satisfies that constraint for all possible realizations of the matrices F0,...,F_k?

(I assume you are using [this definition](https://epubs.siam.org/doi/10.1137/1.9780898717716.ch7) of an interval matrix)

RAYEN does not support LMI interval matrix constraints per se, but if there is a way to transform it to a standard LMI constraint then it will support it. 

We also welcome pull requests with new features.

**Comment by marwaSaid** [comment]
Hi @jtorde ,

The output y needs to lies within a certain set, usually expressed as an interval, but it is not a constant one, it depends on the input each time
Can something like this be feasible?

**Comment by jtorde** [comment]
In general, RAYEN does not support changing constraints right now (i.e., the parameters that define the constraints need to be constant)

However, there are some simple cases (for example y \in [a,b] where a and b are real numbers that depend on the input), where you can force that constraint by using a sigmoid (or tanh) and shifting/scaling it so that the output lies in [a,b]
